# Generated by Django 5.2.1 on 2026-02-20 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_chatmessage_media_url_alter_chatthread_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('sector', models.CharField(choices=[('retail', 'Retail / Kiosk'), ('services', 'Services (Boda, Salon, etc.)'), ('wholesale', 'Wholesale / Mitumba'), ('agri', 'Agribusiness'), ('other', 'Other')], default='retail', max_length=20)),
                ('location', models.CharField(blank=True, help_text='e.g. Gikomba, CBD, Eastleigh', max_length=255)),
                ('inventory_size', models.CharField(blank=True, max_length=50)),
                ('monthly_revenue_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
