# Generated by Django 5.2.1 on 2026-02-20 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_businessgoal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='business_docs/%Y/%m/%d/')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('sales', 'Sales Record'), ('inventory', 'Inventory List'), ('expenses', 'Expense Sheet'), ('other', 'Other')], default='sales', max_length=20)),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
